#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS =  -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/sixgo

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/sixgo

OBJ_DEBUG = $(OBJDIR_DEBUG)/sixgo_computer/StepGenerator.o $(OBJDIR_DEBUG)/sixgo_computer/sixgo.o $(OBJDIR_DEBUG)/sixgo_computer/hash.o $(OBJDIR_DEBUG)/sixgo_computer/base.o $(OBJDIR_DEBUG)/sixgo_computer/ChessManual.o $(OBJDIR_DEBUG)/sixgo_computer/Seach.o $(OBJDIR_DEBUG)/sixgo_computer/MaintainInfo.o $(OBJDIR_DEBUG)/sixgo_computer/LineTypeTable.o $(OBJDIR_DEBUG)/sixgo_computer/Debug.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/sixgo_computer/StepGenerator.o $(OBJDIR_RELEASE)/sixgo_computer/sixgo.o $(OBJDIR_RELEASE)/sixgo_computer/hash.o $(OBJDIR_RELEASE)/sixgo_computer/base.o $(OBJDIR_RELEASE)/sixgo_computer/ChessManual.o $(OBJDIR_RELEASE)/sixgo_computer/Seach.o $(OBJDIR_RELEASE)/sixgo_computer/MaintainInfo.o $(OBJDIR_RELEASE)/sixgo_computer/LineTypeTable.o $(OBJDIR_RELEASE)/sixgo_computer/Debug.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/sixgo_computer || mkdir -p $(OBJDIR_DEBUG)/sixgo_computer

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/sixgo_computer/StepGenerator.o: sixgo_computer/StepGenerator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sixgo_computer/StepGenerator.cpp -o $(OBJDIR_DEBUG)/sixgo_computer/StepGenerator.o

$(OBJDIR_DEBUG)/sixgo_computer/sixgo.o: sixgo_computer/sixgo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sixgo_computer/sixgo.cpp -o $(OBJDIR_DEBUG)/sixgo_computer/sixgo.o

$(OBJDIR_DEBUG)/sixgo_computer/hash.o: sixgo_computer/hash.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sixgo_computer/hash.cpp -o $(OBJDIR_DEBUG)/sixgo_computer/hash.o

$(OBJDIR_DEBUG)/sixgo_computer/base.o: sixgo_computer/base.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sixgo_computer/base.cpp -o $(OBJDIR_DEBUG)/sixgo_computer/base.o

$(OBJDIR_DEBUG)/sixgo_computer/ChessManual.o: sixgo_computer/ChessManual.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sixgo_computer/ChessManual.cpp -o $(OBJDIR_DEBUG)/sixgo_computer/ChessManual.o

$(OBJDIR_DEBUG)/sixgo_computer/Seach.o: sixgo_computer/Seach.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sixgo_computer/Seach.cpp -o $(OBJDIR_DEBUG)/sixgo_computer/Seach.o

$(OBJDIR_DEBUG)/sixgo_computer/MaintainInfo.o: sixgo_computer/MaintainInfo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sixgo_computer/MaintainInfo.cpp -o $(OBJDIR_DEBUG)/sixgo_computer/MaintainInfo.o

$(OBJDIR_DEBUG)/sixgo_computer/LineTypeTable.o: sixgo_computer/LineTypeTable.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sixgo_computer/LineTypeTable.cpp -o $(OBJDIR_DEBUG)/sixgo_computer/LineTypeTable.o

$(OBJDIR_DEBUG)/sixgo_computer/Debug.o: sixgo_computer/Debug.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c sixgo_computer/Debug.cpp -o $(OBJDIR_DEBUG)/sixgo_computer/Debug.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/sixgo_computer

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/sixgo_computer || mkdir -p $(OBJDIR_RELEASE)/sixgo_computer

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/sixgo_computer/StepGenerator.o: sixgo_computer/StepGenerator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sixgo_computer/StepGenerator.cpp -o $(OBJDIR_RELEASE)/sixgo_computer/StepGenerator.o

$(OBJDIR_RELEASE)/sixgo_computer/sixgo.o: sixgo_computer/sixgo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sixgo_computer/sixgo.cpp -o $(OBJDIR_RELEASE)/sixgo_computer/sixgo.o

$(OBJDIR_RELEASE)/sixgo_computer/hash.o: sixgo_computer/hash.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sixgo_computer/hash.cpp -o $(OBJDIR_RELEASE)/sixgo_computer/hash.o

$(OBJDIR_RELEASE)/sixgo_computer/base.o: sixgo_computer/base.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sixgo_computer/base.cpp -o $(OBJDIR_RELEASE)/sixgo_computer/base.o

$(OBJDIR_RELEASE)/sixgo_computer/ChessManual.o: sixgo_computer/ChessManual.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sixgo_computer/ChessManual.cpp -o $(OBJDIR_RELEASE)/sixgo_computer/ChessManual.o

$(OBJDIR_RELEASE)/sixgo_computer/Seach.o: sixgo_computer/Seach.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sixgo_computer/Seach.cpp -o $(OBJDIR_RELEASE)/sixgo_computer/Seach.o

$(OBJDIR_RELEASE)/sixgo_computer/MaintainInfo.o: sixgo_computer/MaintainInfo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sixgo_computer/MaintainInfo.cpp -o $(OBJDIR_RELEASE)/sixgo_computer/MaintainInfo.o

$(OBJDIR_RELEASE)/sixgo_computer/LineTypeTable.o: sixgo_computer/LineTypeTable.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sixgo_computer/LineTypeTable.cpp -o $(OBJDIR_RELEASE)/sixgo_computer/LineTypeTable.o

$(OBJDIR_RELEASE)/sixgo_computer/Debug.o: sixgo_computer/Debug.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c sixgo_computer/Debug.cpp -o $(OBJDIR_RELEASE)/sixgo_computer/Debug.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/sixgo_computer

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

